services:
  - type: web
    name: wordfam-api
    env: python
    buildCommand: "pip install -r requirements.txt && python -c 'import nltk; nltk.download(\"wordnet\"); nltk.download(\"omw-1.4\")'"
    startCommand: "uvicorn app:app --host 0.0.0.0 --port $PORT"
    envVars:
      - key: PYTHON_VERSION
        value: 3.10.0
